name: Format

on:
  push:
    branches: [main]
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: "17"
          check-path: "."
          exclude-regex: '^\./(build|managed_components)/.*'

  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@v2
      - run: editorconfig-checker
